version: "3.9"
services:
python: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
  container_name: python
  image: aimvector/python:1.0.0
  build:
    context: ./python
    target: debug
  volumes:
  - ./python/src/:/work
   ports:
     - 5003:5000
     - 5678:5678
